// ⭐️ ИСПРАВЛЕНО: Умный выбор адреса
// Если мы разрабатываем (DEV) -> http://localhost:3000
// Если мы в продакшене (Vercel) -> "" (пустая строка, то есть текущий домен)
// ⭐️ ЖЕЛЕЗОБЕТОННО: Всегда используем текущий домен
// In dev (Vite) the frontend runs on :5173 and the local API server runs on :3000.
// Use explicit localhost:3000 in dev to avoid 404 from vite dev server.
export const API_BASE_URL = (import.meta as any).env?.DEV ? 'http://localhost:3000' : '';

// Optional bypass token support (development only). If a generated bypass token file exists
// the client will append Vercel protection bypass query params to API requests so the
// runtime will not be intercepted by Vercel Deployment Protection.
// no bypass token in final build

export type ApiAnalysisResponse = {
  analysis: string
  isPro: boolean
  brief: boolean
  briefReason?: string
  source?: 'ai' | 'stub'
  // Данные для "живой матрицы"
  matrixData?: {
    keyNumber?: number
    summary?: string
    traits?: string[]
    energies?: number[]
  }
}

export const api = {
  // Этот метод автоматически подставит правильный API_BASE_URL
  async post<T>(url: string, body: unknown): Promise<T> {
    // Пытаемся получить ID из Telegram WebApp (если есть)
    const sdkUserId = (window as any)?.Telegram?.WebApp?.initDataUnsafe?.user?.id;
    
    let bodyWithUser: any;
    if (typeof body === 'object' && body !== null) {
      bodyWithUser = { ...(body as any) };
      // Если userId не передан явно, добавляем его из Telegram
      if (!bodyWithUser.userId && sdkUserId) {
        bodyWithUser.userId = sdkUserId.toString();
      }
    } else {
      bodyWithUser = { userId: sdkUserId, payload: body };
    }

  // ⭐️ ВАЖНО: Собираем полный адрес
  const fullUrl = `${API_BASE_URL}${url}`;

    const res = await fetch(fullUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(bodyWithUser),
    });

    if (!res.ok) {
      const text = await res.text();
      throw new Error(text || `Error ${res.status}`);
    }
    
    return await res.json() as T;
  },
  
  async get<T>(url: string, opts?: { headers?: Record<string,string> }): Promise<T> {
  const fullUrl = `${API_BASE_URL}${url}`;
  // avoid stale 304 from CDN or browser cache in admin console
  const res = await fetch(fullUrl, { headers: opts?.headers, cache: 'no-store' as RequestCache });
    if (!res.ok) {
      throw new Error(await res.text());
    }
  // Some platforms may return empty body for 204/304; guard against parse errors
  const text = await res.text();
  if (!text) return {} as T;
  try { return JSON.parse(text) as T } catch { return (text as unknown) as T }
  },

  // admin-specific GET which will include Basic auth stored in localStorage under 'admin:basic'
  async adminGet<T>(url: string): Promise<T> {
    const token = (() => { try { return localStorage.getItem('admin:basic') } catch { return null } })()
    const headers: Record<string,string> = {}
    if (token) headers['Authorization'] = `Basic ${token}`
    return this.get<T>(url, { headers })
  }
};